[package]
name = "bolomoty"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.58"
colored = "3.1.1"
ignore = "0.4.25"
rayon = "1.11.0"
serde = "1.0.228"
serde_json = "1.0.149"
tree-sitter = "0.26.5"
tree-sitter-python = "0.25.0"
tree-sitter-rust = "0.24.0"
